# A179180
""" 

Each new term in the Fibonacci sequence is generated by adding the
previous two terms.  Starting with 1 and 2, the first 10 terms will be: 1,
2, 3, 5, 8, 13, 21, 34, 55, 89.

Every positive integer can be uniquely written as a sum of nonconsecutive
terms of the Fibonacci sequence. For example, 100 = 3 + 8 + 89.  Such a
sum is called the Zeckendorf representation of the number.

...
"""
import euler
import itertools

@euler.in_mem_memoize
def zfib(n):
    assert(n >= 1)
    if n == 1 or n == 2:
        return n
    return zfib(n-1) + zfib(n-2)

def zeckendorf(n):
    # zeckendofr representation of n (write n as a sum of 
    # non-consecutive Fibonacci numbers). See A007895
    if n == 0:
        return 0
    else:
        for i in itertools.count(start=2):
            if zfib(i) > n:
                return 1 + zeckendorf(n - zfib(i-1))
    assert(1==0)

def testcase1():
    cnt = 0
    for i in xrange(1, 10**6):
        z = zeckendorf(i)
        cnt += z
    assert cnt == 7894453

cnt = 0
for i in xrange(1, 10**4):
    z = zeckendorf(i)
    cnt += z
    print i, cnt
 
#i = 1
#while zfib(i) < 10**17:
    #print zfib(i)
    #i+=1
